export const moviesData=[
    {
        id:Math.random(),
        image:"https://m.media-amazon.com/images/I/819S9CGB5nL._SL1367_.jpg",
        rating:5,
        name:"Star wars: The Rise Of Skywalker",
        date:"December 2019",
        description:'The Rise of Skywalker film is the conclusion of the Skywalker saga. New legends will be born in this epic battle for freedom.',
        trailerVideoLink:'https://www.youtube.com/watch?v=8Qn_spdM5Zg&ab_channel=StarWars',
    },
    {
        id:Math.random(),
        image:"https://fr.web.img4.acsta.net/pictures/18/04/05/16/25/3438394.jpg",
        rating:4,
        name:"Avengers: Infinity War",
        date:"April 2018",
        description:'The Avengers and their allies will have to be ready to sacrifice everything to neutralize the fearsome Thanos before his lightning attack leads to the complete destruction of the universe.',
        trailerVideoLink:'https://www.youtube.com/watch?v=6ZfuNTqbHE8&ab_channel=MarvelEntertainment',
    },
    {
        id:Math.random(),
        image:"https://fr.web.img6.acsta.net/pictures/22/03/09/14/34/2160526.jpg",
        rating:3,
        name:"The Contractor",
        date:"March 2022",
        description:'After being fired from the Marines, James Harper joins a paramilitary organization to support his family. He travels to Poland with an elite team on a mission to investigate a mysterious threat. But Harper finds himself alone and hunted in the middle of Eastern Europe. He will have to fight to stay alive long enough to discover the reasons of those who betrayed him.',
        trailerVideoLink:'https://www.youtube.com/watch?v=e7glvM8Xh0w&ab_channel=ParamountMovies',
    },
    {
        id:Math.random(),
        image:"https://images-na.ssl-images-amazon.com/images/I/91Lrre8epBL._RI_.jpg",
        rating:4,
        name:"Blacklight",
        date:"February 2022",
        description:'Travis Block steps in on behalf of the FBI when all other options have been exhausted. His methods often involve the hard way. When he is ordered to silence an agent who wishes to reveal the methods of the Bureau to the press, he understands that he has become the pawn of a terrible plot. Determined to bring out the truth, he launches into a fight against those with whom he is used to working. But when his adversaries prey on his loved ones, Travis turns his methods against his former employers and he will have no mercy.',
        trailerVideoLink:'https://www.youtube.com/watch?v=PE04ESdgnHI&ab_channel=MovieclipsTrailers',
    },
    {
        id:Math.random(),
        image:"https://imgsrc.cineserie.com/2021/07/1941554.jpg?ver=1",
        rating:4,
        name:"Ida Red",
        date:"April 2022",
        description:'A criminal must deal with a terminal illness while serving her 25-year prison sentence. She encourages her son Wyatt to stay on the straight and narrow and take over the family business. Soon a case gone wrong leads the FBI and local detectives to become more and more interested in Wyatt and his uncle...',
        trailerVideoLink:'https://www.youtube.com/watch?v=8gLlJu0jML8&ab_channel=ParamountMovies',
    },
    {
        id:Math.random(),
        image:"https://fr.web.img5.acsta.net/pictures/22/02/16/17/42/3125788.jpg",
        rating:5,
        name:"The Batman",
        date:"April 2022",
        description:"Two years of walking the streets as Batman and instilling fear in criminals have brought Bruce Wayne to the heart of Gotham's darkness. With only a few trusted allies among the city's corrupt network of high-profile officials and figures, the lone vigilante has established himself as the sole embodiment of revenge among his fellow citizens. When a killer targets Gotham's elite with a series of sadistic schemes, a trail of cryptic clues launches the world's greatest detective on an investigation into the underworld, where he encounters characters like Catwoman, The Penguin, Carmine Falcone and The Riddler. As the evidence mounts and the evildoer's plan becomes clear, Batman must forge new relationships, unmask the culprit, and restore some justice amid the abuse of power and corruption that has long plagued Gotham.",
        trailerVideoLink:'https://www.youtube.com/watch?v=zL4LFSbFPcw&ab_channel=IGN',
    },
]